version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: daily
      time: "08:00"
      timezone: "Asia/Tokyo"
    allow:
      - dependency-type: direct
      - dependency-type: indirect
        dependency-name: "caniuse-lite"
    versioning-strategy: increase
    open-pull-requests-limit: 10
