name: Dependabot Auto-merge

on:
  workflow_run:
    types:
      - completed
    workflows:
      - Test

permissions:
  contents: write
  pull-requests: write

jobs:
  auto_merge:
    name: Auto-merge
    runs-on: ubuntu-latest
    if: github.event.workflow_run.conclusion == 'success' && github.actor == 'dependabot[bot]'

    steps:
      - uses: fastify/github-action-merge-dependabot@v3
