name: Test

on:
  schedule:
    - cron: '0 17 1 * *'
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

permissions:
  contents: read

jobs:
  module_test_node:
    name: ES Modules Test (Node.js)
    runs-on: ubuntu-latest
    if: |
      github.event_name == 'schedule' ||
      github.event_name == 'push' ||
      (github.event_name == 'pull_request' && github.actor != 'dependabot[bot]')

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: 'lts/*'

      - run: node test/src/index.mjs

  module_test_deno:
    name: ES Modules Test (Deno)
    runs-on: ubuntu-latest
    if: |
      github.event_name == 'schedule' ||
      github.event_name == 'push' ||
      (github.event_name == 'pull_request' && github.actor != 'dependabot[bot]')

    steps:
      - uses: actions/checkout@v2

      - uses: denoland/setup-deno@v1
        with:
          deno-version: vx.x.x

      - run: deno run test/src/index.mjs

  unit_test:
    name: Unit Test & Coverage
    runs-on: ubuntu-latest
    if: |
      github.event_name == 'schedule' ||
      github.event_name == 'push' ||
      (github.event_name == 'pull_request' && github.actor != 'dependabot[bot]')

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v2
        with:
          node-version: 'lts/*'

      - name: Install dependencies
        run: yarn --frozen-lockfile
      - run: yarn build:lib
        env:
          NODE_ENV: test

      - run: yarn test

      - uses: codecov/codecov-action@v2
        with:
          flags: unittests

  browser_test:
    name: Browser Test
    runs-on: ubuntu-latest
    if: |
      github.event_name == 'schedule' ||
      github.event_name == 'push' ||
      (github.event_name == 'pull_request' && github.actor != 'dependabot[bot]')

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v2
        with:
          node-version: 'lts/*'

      - uses: saucelabs/sauce-connect-action@v1
        with:
          username: ${{ secrets.SAUCE_USERNAME }}
          accessKey: ${{ secrets.SAUCE_ACCESS_KEY }}
          tunnelIdentifier: github-action-tunnel

      - name: Install dependencies
        run: yarn --frozen-lockfile
      - run: yarn build:browser
        env:
          NODE_ENV: test

      - run: yarn docs

      - name: Start Server
        run: |
          yarn setup-test-browser
          sleep 5
      - run: yarn test-browser
        env:
          SAUCE_USERNAME: ${{ secrets.SAUCE_USERNAME }}
          SAUCE_ACCESS_KEY: ${{ secrets.SAUCE_ACCESS_KEY }}
