name: Test & Coverage

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: yarn --frozen-lockfile
      - run: yarn build:lib
        env:
          NODE_ENV: test

      - run: yarn test

      - uses: codecov/codecov-action@v2
        with:
          flags: unittests
